/**
 * Professional report generator for legal research conversations.
 * Supports PDF, DOCX, and Markdown formats.
 */
import { jsPDF } from "jspdf"
import "jspdf-autotable"
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle } from "docx"
import { saveAs } from "file-saver"
import type { Message } from "@/types"

interface ReportOptions {
  title: string
  conversationId: string
  messages: Message[]
  officerName?: string
  badgeNumber?: string
  department?: string
}

/**
 * Generate Markdown report
 */
export function generateMarkdownReport(options: ReportOptions): string {
  const { title, conversationId, messages, officerName, badgeNumber, department } = options

  let md = `# Wisconsin Legal Research Report\n\n`
  md += `## Case Information\n\n`
  md += `- **Report Title**: ${title}\n`
  md += `- **Report ID**: ${conversationId}\n`
  md += `- **Generated**: ${new Date().toLocaleString()}\n`
  if (officerName) md += `- **Officer**: ${officerName}\n`
  if (badgeNumber) md += `- **Badge Number**: ${badgeNumber}\n`
  if (department) md += `- **Department**: ${department}\n`
  md += `\n---\n\n`

  md += `## Legal Research Summary\n\n`
  md += `This report contains ${messages.length} entries documenting legal research queries and responses related to Wisconsin law enforcement matters.\n\n`
  md += `---\n\n`

  messages.forEach((msg, index) => {
    const isQuery = msg.role === "user"
    const timestamp = new Date(msg.timestamp).toLocaleString()

    if (isQuery) {
      md += `### Query ${Math.floor(index / 2) + 1}\n\n`
      md += `**Time**: ${timestamp}\n\n`
      md += `**Question**:\n${msg.content}\n\n`
    } else {
      md += `**Legal Response**:\n\n`
      md += `${msg.content}\n\n`

      if (msg.confidence) {
        md += `**Confidence Level**: ${msg.confidence.toUpperCase()}\n\n`
      }

      if (msg.is_sensitive) {
        md += `> ⚠️ **SENSITIVE TOPIC** - This matter requires special legal consideration and consultation with legal counsel.\n\n`
      }

      if (msg.sources && msg.sources.length > 0) {
        md += `#### Sources Referenced\n\n`
        msg.sources.forEach((source, i) => {
          md += `${i + 1}. **${source.metadata.title}**\n`
          if (source.metadata.statute_num) {
            md += `   - Statute: § ${source.metadata.statute_num}\n`
          }
          if (source.metadata.jurisdiction) {
            md += `   - Jurisdiction: ${source.metadata.jurisdiction}\n`
          }
          if (source.metadata.effective_date) {
            md += `   - Effective Date: ${source.metadata.effective_date}\n`
          }
          md += `   - Relevance: ${Math.round(source.score * 100)}%\n`
          if (source.metadata.cross_references && source.metadata.cross_references.length > 0) {
            md += `   - Related Statutes: ${source.metadata.cross_references.map(r => `§ ${r.target}`).join(', ')}\n`
          }
          md += `\n`
        })
      }

      md += `---\n\n`
    }
  })

  md += `## Legal Disclaimer\n\n`
  md += `This report contains legal information for Wisconsin law enforcement, not legal advice. All information should be verified with current statutes and department policies. Always consult your department's legal counsel for specific situations and before taking action on sensitive matters.\n\n`
  md += `**Report generated by Wisconsin Legal Assistant** | ${new Date().toLocaleString()}\n`

  return md
}

/**
 * Export Markdown report
 */
export function exportMarkdownReport(options: ReportOptions): void {
  const markdown = generateMarkdownReport(options)
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" })
  saveAs(blob, `legal-research-report-${options.conversationId}.md`)
}

/**
 * Generate and export PDF report
 */
export function exportPDFReport(options: ReportOptions): void {
  const { title, conversationId, messages, officerName, badgeNumber, department } = options

  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(18)
  doc.setFont("helvetica", "bold")
  doc.text("Wisconsin Legal Research Report", 14, yPosition)
  yPosition += 10

  // Case Information
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text(`Report ID: ${conversationId}`, 14, yPosition)
  yPosition += 5
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, yPosition)
  yPosition += 5
  if (officerName) {
    doc.text(`Officer: ${officerName}`, 14, yPosition)
    yPosition += 5
  }
  if (badgeNumber) {
    doc.text(`Badge: ${badgeNumber}`, 14, yPosition)
    yPosition += 5
  }
  if (department) {
    doc.text(`Department: ${department}`, 14, yPosition)
    yPosition += 5
  }
  yPosition += 5

  // Draw line
  doc.setDrawColor(200, 200, 200)
  doc.line(14, yPosition, 196, yPosition)
  yPosition += 10

  // Process messages
  messages.forEach((msg, index) => {
    if (yPosition > 270) {
      doc.addPage()
      yPosition = 20
    }

    const isQuery = msg.role === "user"
    const timestamp = new Date(msg.timestamp).toLocaleString()

    if (isQuery) {
      // Query header
      doc.setFontSize(12)
      doc.setFont("helvetica", "bold")
      doc.text(`Query ${Math.floor(index / 2) + 1}`, 14, yPosition)
      yPosition += 6

      doc.setFontSize(9)
      doc.setFont("helvetica", "italic")
      doc.text(`Time: ${timestamp}`, 14, yPosition)
      yPosition += 6

      // Query text
      doc.setFont("helvetica", "normal")
      const queryLines = doc.splitTextToSize(msg.content, 180)
      doc.text(queryLines, 14, yPosition)
      yPosition += queryLines.length * 5 + 5
    } else {
      // Response header
      doc.setFontSize(11)
      doc.setFont("helvetica", "bold")
      doc.text("Legal Response:", 14, yPosition)
      yPosition += 6

      // Response text
      doc.setFontSize(9)
      doc.setFont("helvetica", "normal")
      const responseLines = doc.splitTextToSize(msg.content, 180)
      responseLines.forEach((line: string) => {
        if (yPosition > 280) {
          doc.addPage()
          yPosition = 20
        }
        doc.text(line, 14, yPosition)
        yPosition += 4
      })
      yPosition += 3

      // Confidence
      if (msg.confidence) {
        doc.setFont("helvetica", "bold")
        doc.text(`Confidence: ${msg.confidence.toUpperCase()}`, 14, yPosition)
        yPosition += 5
      }

      // Sensitive warning
      if (msg.is_sensitive) {
        doc.setTextColor(220, 38, 38)
        doc.setFont("helvetica", "bold")
        doc.text("⚠ SENSITIVE TOPIC - Consult legal counsel", 14, yPosition)
        doc.setTextColor(0, 0, 0)
        yPosition += 6
      }

      // Sources
      if (msg.sources && msg.sources.length > 0) {
        if (yPosition > 260) {
          doc.addPage()
          yPosition = 20
        }

        doc.setFont("helvetica", "bold")
        doc.text("Sources:", 14, yPosition)
        yPosition += 5

        msg.sources.slice(0, 5).forEach((source, i) => {
          if (yPosition > 275) {
            doc.addPage()
            yPosition = 20
          }

          doc.setFont("helvetica", "normal")
          doc.setFontSize(8)
          doc.text(`${i + 1}. ${source.metadata.title}`, 18, yPosition)
          yPosition += 4

          if (source.metadata.statute_num) {
            doc.text(`   § ${source.metadata.statute_num}`, 22, yPosition)
            yPosition += 3
          }
          if (source.metadata.effective_date) {
            doc.text(`   Effective: ${source.metadata.effective_date}`, 22, yPosition)
            yPosition += 3
          }
          yPosition += 2
        })

        doc.setFontSize(9)
      }

      yPosition += 5
      doc.setDrawColor(230, 230, 230)
      doc.line(14, yPosition, 196, yPosition)
      yPosition += 8
    }
  })

  // Footer disclaimer
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(8)
  doc.setFont("helvetica", "italic")
  doc.setTextColor(100, 100, 100)
  const disclaimer = "DISCLAIMER: This report contains legal information for Wisconsin law enforcement, not legal advice. Always consult your department's legal counsel for specific situations."
  const disclaimerLines = doc.splitTextToSize(disclaimer, 180)
  doc.text(disclaimerLines, 14, yPosition)

  // Save PDF
  doc.save(`legal-research-report-${conversationId}.pdf`)
}

/**
 * Generate and export DOCX report
 */
export async function exportDOCXReport(options: ReportOptions): Promise<void> {
  const { title, conversationId, messages, officerName, badgeNumber, department } = options

  const children: (Paragraph | Table)[] = []

  // Title
  children.push(
    new Paragraph({
      text: "Wisconsin Legal Research Report",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  )

  // Case information table
  const caseInfoRows = [
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph({ text: "Report ID", bold: true })] }),
        new TableCell({ children: [new Paragraph(conversationId)] }),
      ],
    }),
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph({ text: "Generated", bold: true })] }),
        new TableCell({ children: [new Paragraph(new Date().toLocaleString())] }),
      ],
    }),
  ]

  if (officerName) {
    caseInfoRows.push(
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ text: "Officer", bold: true })] }),
          new TableCell({ children: [new Paragraph(officerName)] }),
        ],
      })
    )
  }

  if (badgeNumber) {
    caseInfoRows.push(
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ text: "Badge Number", bold: true })] }),
          new TableCell({ children: [new Paragraph(badgeNumber)] }),
        ],
      })
    )
  }

  if (department) {
    caseInfoRows.push(
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ text: "Department", bold: true })] }),
          new TableCell({ children: [new Paragraph(department)] }),
        ],
      })
    )
  }

  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: caseInfoRows,
    }),
    new Paragraph({ text: "", spacing: { after: 300 } })
  )

  // Process messages
  messages.forEach((msg, index) => {
    const isQuery = msg.role === "user"
    const timestamp = new Date(msg.timestamp).toLocaleString()

    if (isQuery) {
      children.push(
        new Paragraph({
          text: `Query ${Math.floor(index / 2) + 1}`,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Time: ", bold: true }),
            new TextRun(timestamp),
          ],
          spacing: { after: 120 },
        }),
        new Paragraph({
          text: msg.content,
          spacing: { after: 200 },
        })
      )
    } else {
      children.push(
        new Paragraph({
          text: "Legal Response:",
          bold: true,
          spacing: { before: 120, after: 120 },
        }),
        new Paragraph({
          text: msg.content,
          spacing: { after: 200 },
        })
      )

      if (msg.confidence) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: "Confidence Level: ", bold: true }),
              new TextRun(msg.confidence.toUpperCase()),
            ],
            spacing: { after: 120 },
          })
        )
      }

      if (msg.is_sensitive) {
        children.push(
          new Paragraph({
            text: "⚠️ SENSITIVE TOPIC - This matter requires special legal consideration and consultation with legal counsel.",
            italics: true,
            color: "DC2626",
            spacing: { after: 200 },
          })
        )
      }

      if (msg.sources && msg.sources.length > 0) {
        children.push(
          new Paragraph({
            text: "Sources Referenced:",
            bold: true,
            spacing: { before: 120, after: 120 },
          })
        )

        msg.sources.forEach((source, i) => {
          const sourceText = [`${i + 1}. ${source.metadata.title}`]
          if (source.metadata.statute_num) sourceText.push(`   Statute: § ${source.metadata.statute_num}`)
          if (source.metadata.jurisdiction) sourceText.push(`   Jurisdiction: ${source.metadata.jurisdiction}`)
          if (source.metadata.effective_date) sourceText.push(`   Effective: ${source.metadata.effective_date}`)
          sourceText.push(`   Relevance: ${Math.round(source.score * 100)}%`)

          children.push(
            new Paragraph({
              text: sourceText.join("\n"),
              spacing: { after: 120 },
            })
          )
        })
      }

      children.push(
        new Paragraph({
          text: "_______________________________________________________________",
          spacing: { before: 200, after: 200 },
        })
      )
    }
  })

  // Disclaimer
  children.push(
    new Paragraph({
      text: "Legal Disclaimer",
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 400, after: 200 },
    }),
    new Paragraph({
      text: "This report contains legal information for Wisconsin law enforcement, not legal advice. All information should be verified with current statutes and department policies. Always consult your department's legal counsel for specific situations and before taking action on sensitive matters.",
      italics: true,
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: `Report generated by Wisconsin Legal Assistant | ${new Date().toLocaleString()}`,
      alignment: AlignmentType.CENTER,
      italics: true,
    })
  )

  const doc = new Document({
    sections: [{
      properties: {},
      children,
    }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `legal-research-report-${conversationId}.docx`)
}
